enum Priority {
  LOW
  MEDIUM
  HIGH
  URGENT
}

enum TicketStatus {
  OPEN
  IN_PROGRESS
  RESOLVED
  CLOSED
}
enum SlaState {
  ON_TRACK
  AT_RISK
  BREACHED
}

type Ticket {
  id: ID!
  title: String!
  description: String!
  priority: Priority!
  status: TicketStatus!
  firstResponseDeadline: String!
resolutionDeadline: String!
slaState: SlaState!
remainingMinutes: Int!

  reporterId: ID!
  assigneeId: ID

  createdAt: String!
  firstResponseAt: String
  resolvedAt: String
}
type PriorityStats {
  LOW: Int!
  MEDIUM: Int!
  HIGH: Int!
  URGENT: Int!
}

type DashboardStats {
  openTickets: Int!
  inProgressTickets: Int!
  resolvedTickets: Int!
  breachedTickets: Int!
  atRiskTickets: Int!
  ticketsByPriority: PriorityStats!
}
type TicketEdge {
  cursor: String!
  node: Ticket!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

type TicketConnection {
  edges: [TicketEdge!]!
  pageInfo: PageInfo!
}

input CreateTicketInput {
  title: String!
  description: String!
  priority: Priority!
}
input AssignTicketInput {
  ticketId: ID!
  assigneeId: ID!
}
input ChangeTicketStatusInput {
  ticketId: ID!
  status: TicketStatus!
}

input TicketFilterInput {
  status: TicketStatus
  priority: Priority
  assigneeId: ID
  slaState: String
  take: Int
  cursor: ID
}

extend type Query {
  tickets(
  filter: TicketFilterInput
  cursor: String
  take: Int = 10
): TicketConnection!
  ticket(id: ID!): Ticket
  dashboardStats: DashboardStats!
}

extend type Mutation {
  createTicket(input: CreateTicketInput!): Ticket!
  assignTicket(input: AssignTicketInput!): Ticket!
  changeTicketStatus(input: ChangeTicketStatusInput!): Ticket!
}