enum Priority {
  LOW
  MEDIUM
  HIGH
  URGENT
}

enum TicketStatus {
  OPEN
  IN_PROGRESS
  RESOLVED
  CLOSED
}

type Ticket {
  id: ID!
  title: String!
  description: String!
  priority: Priority!
  status: TicketStatus!

  reporterId: ID!
  assigneeId: ID

  createdAt: String!
  firstResponseAt: String
  resolvedAt: String
}

input CreateTicketInput {
  title: String!
  description: String!
  priority: Priority!
}
input AssignTicketInput {
  ticketId: ID!
  assigneeId: ID!
}
input ChangeTicketStatusInput {
  ticketId: ID!
  status: TicketStatus!
}

input TicketFilterInput {
  status: TicketStatus
  priority: Priority
  assigneeId: ID
  slaState: String
  take: Int
  cursor: ID
}

extend type Query {
  tickets(filter: TicketFilterInput): [Ticket!]!
  ticket(id: ID!): Ticket
}

extend type Mutation {
  createTicket(input: CreateTicketInput!): Ticket!
  assignTicket(input: AssignTicketInput!): Ticket!
  changeTicketStatus(input: ChangeTicketStatusInput!): Ticket!
}